### PR TITLE
upgraded hls.js and videojs

### PR DESCRIPTION
**Pull request by aronallen**
Hi, I upgraded this plugin to support videojs 5, and in the mean time I also upgraded hlsjs.
This addresses #1

### CODE REVIEW

**Comment by benjipott** [comment]
:+1:  ok for merge

**Comment by aronallen** [comment]
@benjipott I don't have merge rights, I also have another pull request pending in my fork. I will get back to you once we are ready.

**Comment by aronallen** [comment]
we are ready for a pull now.

**Comment by benjipott** [comment]
Many thks!

**Pull request merged**
